import { Roboto } from "next/font/google";
import "./globals.css";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"]
})
export const metadata = {
  title: "Display-Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased overflow-x-hidden`}
      >
        {children}
        <ScrollToTopButton/>
      </body>
    </html>
  );
}
